New upstream version 1.1.2~rc1

diff --git a/tools/virt-xml-validate.in b/tools/virt-xml-validate.in
--- a/tools/virt-xml-validate.in
+++ b/tools/virt-xml-validate.in
@@ -17,22 +17,48 @@
 
 set -e
 
+case $1 in
+  -h | --h | --he | --hel | --help)
+    cat <<EOF
+Usage:
+  $0 XML-FILE [SCHEMA-NAME]
+  $0 OPTION
+
+Options:
+  -h | --help        Display program help
+  -V | --version     Display program version
+EOF
+    exit ;;
+  -V | --v | --ve | --ver | --vers | --versi | --versio | --version)
+    cat <<EOF
+$0 (libvirt) @VERSION@
+EOF
+    exit ;;
+  --) shift ;;
+  -*)
+    echo "$0: unrecognized option '$1'" >&2
+    exit 1 ;;
+esac
+
 XMLFILE="$1"
 TYPE="$2"
 
 if [ -z "$XMLFILE" ]; then
-  echo "syntax: $0 XMLFILE [TYPE]"
+  echo "syntax: $0 XMLFILE [TYPE]" >&2
   exit 1
 fi
 
 if [ ! -f "$XMLFILE" ]; then
-  echo "$0: document $XMLFILE does not exist"
+  echo "$0: document $XMLFILE does not exist" >&2
   exit 2
 fi
 
 if [ -z "$TYPE" ]; then
   ROOT=`xmllint --stream --debug "$XMLFILE" 2>/dev/null | grep "^0 1 " | awk '{ print $3 }'`
   case "$ROOT" in
+     *domainsnapshot*) # Must come first, since *domain* is a substring
+        TYPE="domainsnapshot"
+        ;;
      *domain*)
         TYPE="domain"
         ;;
@@ -51,8 +77,14 @@ if [ -z "$TYPE" ]; then
      *device*)
         TYPE="nodedev"
         ;;
+     *filter*)
+        TYPE="nwfilter"
+        ;;
+     *secret*)
+        TYPE="secret"
+        ;;
      *)
-       echo "$0: cannot determine schema type for $XMLFILE"
+       echo "$0: cannot determine schema type for $XMLFILE" >&2
        exit 3
   esac
 fi
@@ -60,13 +92,13 @@ fi
 SCHEMA="@schemadir@/${TYPE}.rng"
 
 if [ ! -f "$SCHEMA" ]; then
-  echo "$0: schema $SCHEMA does not exist"
+  echo "$0: schema $SCHEMA does not exist" >&2
   exit 4
 fi
 
 xmllint --noout --relaxng "$SCHEMA" "$XMLFILE"
 
-exit 0
+exit
 
 : <<=cut
 =pod
@@ -78,6 +110,7 @@ exit 0
 =head1 SYNOPSIS
 
   virt-xml-validate XML-FILE [SCHEMA-NAME]
+  virt-xml-validate OPTION
 
 =head1 DESCRIPTION
 
@@ -117,6 +150,20 @@ The schema for the XML format used to declare driver capabilities
 
 =back
 
+=head1 OPTIONS
+
+=over
+
+=item B<-h, --help>
+
+Display command line help usage then exit.
+
+=item B<-V, --version>
+
+Display version information then exit.
+
+=back
+
 =head1 EXIT STATUS
 
 Upon successful validation, an exit status of 0 will be set. Upon
@@ -134,7 +181,7 @@ Alternatively report bugs to your software distributor / vendor.
 
 =head1 COPYRIGHT
 
-Copyright (C) 2009-2012 by Red Hat, Inc.
+Copyright (C) 2009-2013 by Red Hat, Inc.
 Copyright (C) 2009 by Daniel P. Berrange
 
 =head1 LICENSE
